[providers]
python = {}

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r App/requirements.txt"
]

[start]
cmd = "bash ./start.sh"
